language: php

php:
  - 5.6
  - 7.0
  - 7.1
cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit -v

after_success:
  - vendor/bin/coveralls -v